# Generated by Django 4.1.3 on 2022-11-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneBook100',
            new_name='PhoneBook',
        ),
    ]
